const axios = require('axios');

const BASE_URL = 'http://localhost:3000/api';

async function testCoupleAnalysis() {
    console.log('--- Starting Encoding-Safe Test ---');

    const payload = {
        chat: "우리는 오늘 서로의 눈을 바라보며 깊은 대화를 나누었습니다. 서로의 소중함을 다시 한번 느꼈습니다.",
        day: 10,
        isSpecialMission: true
    };

    try {
        const response = await axios.post(`${BASE_URL}/analysis/couple-chat`, payload);
        const data = response.data;

        console.log('Status:', response.status);

        if (data.analysis && data.feedback && data.nextMission) {
            console.log('[SUCCESS] All fields present.');
            console.log('Analysis Length:', data.analysis.length);
            console.log('Feedback Length:', data.feedback.length);
            console.log('Mission (Base64):', Buffer.from(data.nextMission).toString('base64'));

            const fallbackMissions = [
                "몰래 편지 써라", "간식 사다줘라", "발 씻겨줘라", "어깨 주물러줘라",
                "먼저 사과해라", "몰래 청소해라", "비타민 챙겨줘라", "신발 정리해라",
                "이불 덮어줘라", "물 한 잔 떠줘라"
            ];

            if (fallbackMissions.includes(data.nextMission)) {
                console.log('[FAILURE] Mission is a FALLBACK.');
            } else {
                console.log('[SUCCESS] Mission is GENERATED by AI.');
            }

            if (data.analysis.includes("AI 분석 데이터 형식 오류") || data.analysis.includes("AI 연결 실패")) {
                console.log('[FAILURE] Analysis is a FALLBACK.');
            } else {
                console.log('[SUCCESS] Analysis is GENERATED by AI.');
            }

        } else {
            console.log('[FAILURE] Missing fields.');
            console.log('Keys:', Object.keys(data));
        }

    } catch (error) {
        console.error('[ERROR]', error.message);
    }
}

testCoupleAnalysis();
